name: school_management_system
description: "A new Flutter project."
publish_to: 'none' # Prevent publishing to pub.dev

# Versioning
version: 1.0.0+1

# Environment
environment:
  sdk: ">=3.8.1 <4.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  # Charts
  fl_chart: ^0.68.0

  # Internationalization
  intl: ^0.18.1

  # Cupertino icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

# Flutter settings
flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

# Launcher icons configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
